<?php
$conf=array(
    'site'=>array(
        'sitelink'=>'https://www.corepublic.space',
        'version'=>'0.1 Dev'
    ),
    'database'=>array(
        'type'=>'json',
        'link'=>'./data/database/'
    ),
    'admin'=>array(
        'name'=>'kengwang',
        'sPassword'=>'73aa44aee7e70fe8d880dad26b1f4a5e'
    ),
    'file'=>array(
        'allowPrefix'=>'phar,jar',
        'savePath'=>'./upload',
        'changePrefix'=>'tmp'
    )
);